### ISSUE TITLE
/content reference

### ISSUE THREAD

**Issue by johndpope** [HemantKArya/HqStableDiffusionColab#1]
is there a better place to / or better way to code this?
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
Input In [9], in <cell line: 2>()
      1 get_ipython().system('git clone https://github.com/TencentARC/GFPGAN.git')
----> 2 os.chdir("/content/GFPGAN")
      5 get_ipython().system('pip install basicsr')
      7 get_ipython().system('pip install facexlib')

FileNotFoundError: [Errno 2] No such file or directory: '/content/GFPGAN'

I'm on ubuntu 22.04 and it doesn't want to create this root directory.

**Comment by HemantKArya** [comment]
I think it is resoloved now you can go through this notebook again... :)
